name: deploy_iselaweb

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.PROJET_ID }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      # CHECK THE DEVELOP INFRA BRANCH AND FETCH SUBMODULES
      - name: Checkout
        uses: actions/checkout@v2
      # SETUP GCLOUD CLI
